# Generated by Django 4.1.1 on 2023-03-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('regno', models.CharField(max_length=5)),
                ('semister', models.CharField(max_length=20)),
                ('courses', models.CharField(max_length=500)),
            ],
        ),
    ]
